#!/bin/sh
# /usr/bin/update-bypass-list
#
# Pulls a fresh Russian bypass-domain list and regenerates
# /etc/dnsmasq.d/allow-domains.conf with two directives per domain:
#
#   nftset=/<domain>/4#inet#fw4#allow_domains_v4
#   nftset=/<domain>/6#inet#fw4#allow_domains_v6
#   server=/<domain>/77.88.8.8
#
# The nftset directives tell dnsmasq to dump resolved IPs into the nft
# sets that the mangle hook in 50-allow-domains.nft matches on.
# The server= directive forces the domain to resolve through a Russian
# upstream (Yandex DNS) over eth0 so we get Russian CDN edge addresses.
#
# Source: github.com/itdoginfo/allow-domains (community-maintained).
# Run manually once, then from cron weekly (/etc/crontabs/root):
#   0 6 * * 0 /usr/bin/update-bypass-list

set -eu

SRC_URL='https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst'
RU_RESOLVER='77.88.8.8'
NFT_TABLE='inet#fw4'
SET_V4='allow_domains_v4'
SET_V6='allow_domains_v6'

OUT_FILE='/etc/dnsmasq.d/allow-domains.conf'
TMP_RAW='/tmp/allow-domains-raw.lst'
TMP_OUT='/tmp/allow-domains.conf.new'
MIN_DOMAINS=100

echo "Fetching ${SRC_URL}"
uclient-fetch -4 --quiet -O "$TMP_RAW" "$SRC_URL"

# Sanity check — protect against empty / half-downloaded file.
COUNT=$(grep -cE '^[a-zA-Z0-9]' "$TMP_RAW" 2>/dev/null || echo 0)
if [ "$COUNT" -lt "$MIN_DOMAINS" ]; then
    echo "ERROR: only $COUNT domains parsed (< $MIN_DOMAINS). Aborting." >&2
    exit 1
fi

echo "# Generated by update-bypass-list.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$TMP_OUT"
echo "# Source: $SRC_URL" >> "$TMP_OUT"
echo "# Domains: $COUNT" >> "$TMP_OUT"

# Skip comments and blank lines, emit three directives per domain.
grep -E '^[a-zA-Z0-9]' "$TMP_RAW" | while IFS= read -r domain; do
    printf 'nftset=/%s/4#%s#%s\n' "$domain" "$NFT_TABLE" "$SET_V4" >> "$TMP_OUT"
    printf 'nftset=/%s/6#%s#%s\n' "$domain" "$NFT_TABLE" "$SET_V6" >> "$TMP_OUT"
    printf 'server=/%s/%s\n' "$domain" "$RU_RESOLVER" >> "$TMP_OUT"
done

mv "$TMP_OUT" "$OUT_FILE"
rm -f "$TMP_RAW"

echo "Wrote $OUT_FILE ($COUNT domains, $(wc -l < "$OUT_FILE") dnsmasq directives)"

/etc/init.d/dnsmasq reload
echo "dnsmasq reloaded"
